neighbornook_backend/event/urls.py
from django.urls import path
from . import views

app_name = "event"

urlpatterns = [
    path('category/<int:category_id>/', views.events_categories, name='events_categories'),
    path('<int:pk>/', views.event_detail, name='event_detail'),
    path('new_event/', views.new_event, name='new_event'),
]

neighbornook_backend/home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home_loggedin, name='home_loggedin'),
]

neighbornook_backend/neighbornook_backend/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('event/', include('event.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

neighbornook_backend/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import UserProfileView, CustomLoginView, custom_logout_view

app_name = "user"

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', custom_logout_view, name='logout'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('profile/<str:username>/', UserProfileView.as_view(), name='user_profile'),
    path('profile_update/', views.profile_update, name='profile_update'),
    path('signup/', views.signup, name='signup'),
]

neighbornook_backend/home/views.py
from django.shortcuts import render
from event.models import Event, EventImage, Category
from weather_api.weather import get_weather_context

def home(request):
    location = '51.5072,-0.1276'
    context = get_weather_context(location)


    return render(request, 'home/home_not_loggedin.html', {
            'user': request.user,
            **context
        })

def home_loggedin(request):
    events = Event.objects.filter(is_active=True).order_by('-date') [0:6]
    categories = Category.objects.all()

    location = '51.5072,-0.1276'
    context = get_weather_context(location)

    return render(request, 'home/home_loggedin.html', {
            **context,
            'user': request.user,
            'events': events,
            'categories': categories,
        })

neighbornook_backend/home/templates/home/home_loggedin.html
{% extends "home/base.html" %}
{% block title %}
    Neighbornook
{% endblock title %}

{% block content %}
    <div class="home_page">
        <div class="container-fluid my-4 home_container">
            <h3 class="border-bottom custom-border register-title mb-4">
                Events Around You
            </h3>
    
            <div class="container">
                <div class="row items-display_container justify-content-center">
                    {% if events|length == 1 %}
                        <div class="col-md-6 d-flex justify-content-center mb-4">
                            <a href="{% url 'event:event_detail' events.0.id %}" class="item-box text-center">
                                <div class="event-images">
                                    {% for image in event.images.all %}
                                        <div class="event-image">
                                            <img src="{{ image.image.url }}" alt="{{ event.name }}" style="width: 100%; height: auto;">
                                        </div>
                                    {% empty %}
                                        <p>No images available.</p>
                                    {% endfor %}
                                </div>
            
                                <div class="item-description mt-2">
                                    <h2 class="item-name">
                                        {{ events.0.name }}
                                    </h2>

                                    <p class="event-item">
                                        {{ events.0.overview }}
                                    </p>
                                    
                                    <p class="event-item">
                                        By: {{ events.0.created_by }}
                                    </p>

                                    <p class="event-item">
                                        {{ event.0.location }}
                                    </p>

                                    <p class="event-item">
                                        {{ event.0.date }}
                                    </p>
                                </div>
                            </a>
                        </div>
                    {% else %}
                        <div class="row event-row">
                            {% for event in events %}
                                <div class="col-md-6 d-flex justify-content-center event-col mb-4">
                                    
                                    <div class="carousel" id="carousel{{ event.id }}">
                                        {% if event.images.all %}
                                            <div class="carousel_inner">
                                                {% for image in event.images.all %}
                                                    <div class="carousel_item {% if forloop.first %}active{% endif %}">
                                                        <img src="{{ image.image.url }}" alt="{{ event.name }}">
                                                    </div>                                                
                                                {% endfor %}
                                            </div>
                                            <button class="carousel-control prev" onclick="prevSlide({{ event.id }})">&#10094;</button>
                                            <button class="carousel-control next" onclick="nextSlide({{ event.id }})">&#10095;</button>
                                        {% else %}
                                            <div class="no_img-container">
                                                <p>No images available</p>
                                            </div>
                                        {% endif %}
                                    </div>
                                    
                        
                                    <a href="{% url 'event:event_detail' event.id %}" class="event-box text-center">
                                        <div class="event-container mt-2">
                                            <h2 class="event-title">
                                                {{ event.name }}
                                            </h2>

        
                                            <p class="event-item event-profile">
                                                <img 
                                                    src="{{ event.created_by.profile.profile_img.url }}" 
                                                    alt="{{ event.created_by.username }}" 
                                                    class="profile-img_event rounded-circle">
                                                {{ event.created_by }}
                                            </p>
    
                                            <div class="event-overview">
                                                <p class="event-item">
                                                    {{ event.overview }}
                                                </p>
                                            </div>
    
                                            <div class="event-time event">
                                                <p class="event-item">
                                                    {{ event.location }}
                                                </p>

                                                <p 
                                                    class="event-item countdown" 
                                                    id="countdown-{{ event.id }}" 
                                                    data-date="{{ event.date }}" 
                                                    data-time="{{ event.time }}">
                                                </p>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    
        <div class="home-categories">
            <div class="container-fluid">
                <h3 class="border-bottom custom-border register-title mb-4">
                    Categories
                </h3>
        
                <div class="px-4 py-4 categories-list">
                    <div class="categories-grid">
                        {% for category in categories %}
                            <div class="category-item">
                                <a href="{% url 'event:events_categories' category.id %}" class="category-link">
                                    <div class="categories-block">
                                            <h4 class="category-name">
                                                {{ category.name }}
                                            </h4>
                                        <p class="category-count text-muted mb-0">
                                            {% if category.event.count > 1 %}
                                                {{ category.event.count }} events
                                            {% else %}
                                                {{ category.event.count }} event
                                            {% endif %}
                                        </p>
                                    </div>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

neighbornook_backend/home/templates/home/home_not_loggedin.html
{% extends "home/base.html" %}
{% block title %}
    Welcome to Neighborhood
{% endblock title %}

{% block not_logged %}

    <header class="site-header not_loggedin">
        <div class="header-content">
            <h1 class="header-title">
                Start your adventure and meet new friends with Neighbornook
            </h1>

            <div class="join-btn">
                <a href="{% url 'user:signup' %}" class="nav-link">
                    Join Now
                </a>
            </div>
        </div>
    </header>

    <main class="mx-5">
        <div class="description">
            <h2 class="not_loggedin_title">
                Connect with locals and make new memories
            </h2>

            <p class="not_loggedin_description">
                Discover events and activities made by your local community where you will meet new people and do fun activities together. 
                Or simply create your own event based on your interests
            </p>
        </div>

        <div class="infinite-carousel">
            <div class="carousel-inner">
                <img src="{{ MEDIA_URL }}carousel/dog-walk.jpg" alt="photo" class="infinite-img">
                <img src="{{ MEDIA_URL }}carousel/group-sun.jpg" alt="photo" class="infinite-img">
                <img src="{{ MEDIA_URL }}carousel/group-out.jpg" alt="photo" class="infinite-img">
                <img src="{{ MEDIA_URL }}carousel/group-in.jpg" alt="photo" class="infinite-img">
                <img src="{{ MEDIA_URL }}carousel/group-night.jpg" alt="photo" class="infinite-img">
                <img src="{{ MEDIA_URL }}carousel/hiking.jpg" alt="photo" class="infinite-img">
                <img src="{{ MEDIA_URL }}carousel/yoga.jpg" alt="photo" class="infinite-img">
            </div>
        </div>

        <div>

            <h2 class="connections-title">
                Get connected to
            </h2>

            <div class="connections">
                <div class="card custom-card">
                    <div class="card-body">
                        <i class="fa-solid fa-user-group"></i>
                        <h5 class="card-title">People</h5>
                        <p class="card-text">Young professionals seeking meaningful connections with like-minded individuals</p>
                    </div>
                </div>

                <div class="card custom-card">
                    <div class="card-body">
                        <i class="fa-solid fa-people-group"></i>
                        <h5 class="card-title">Groups</h5>
                        <p class="card-text">Curated communities to stay connected with soulmates</p>
                    </div>
                </div>

                <div class="card custom-card">
                    <div class="card-body">
                        <i class="fa-solid fa-cloud-sun"></i>
                        <h5 class="card-title">Activities</h5>
                        <p class="card-text">Explore and join activities organized by our community</p>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock not_logged %}