neighbornook_backend/home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home_loggedin, name='home_loggedin'),
]

neighbornook_backend/neighbornook_backend/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('event/', include('event.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

neighbornook_backend/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import UserProfileView, CustomLoginView, custom_logout_view

app_name = "user"

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', custom_logout_view, name='logout'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('profile/<str:username>/', UserProfileView.as_view(), name='user_profile'),
    path('profile_update/', views.profile_update, name='profile_update'),
    path('signup/', views.signup, name='signup'),
]

neighbornook_backend/user/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    profile_img = models.ImageField(default='default.png', upload_to='profile_imgs')

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name} Profile'
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.profile_img.path)

        if img.width > 300 or img.height > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.profile_img.path)

neighbornook_backend/user/forms.py
from django import forms 
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError
from .models import Profile

def custom_char_field(placeholder, input_type='text', **kwargs):
    attrs = {
        'placeholder': placeholder,
        'class': 'auth_inputs',
    }
    attrs.update(kwargs)
    
    widget = forms.TextInput(attrs=attrs)
    if input_type == 'password':
        widget = forms.PasswordInput(attrs=attrs)
    
    return forms.CharField(widget=widget)

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')
    profile_img = forms.ImageField(required=False)
    bio = forms.CharField(required=False, widget=forms.Textarea)

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username', 
            'email', 
            'password1', 
            'password2',
            'bio',
            'profile_img',
        )

    first_name = custom_char_field('First Name')
    last_name = custom_char_field('Last Name')
    username = custom_char_field('Username')
    email = custom_char_field('Email')
    password1 = forms.CharField(label='Password', 
                                widget=forms.PasswordInput(
                                    attrs={
                                        'class': 'password-toggle auth_inputs password', 
                                        'placeholder': 'Your Password',
                                    }
                                ))
    password2 = forms.CharField(label='Confirm Password', 
                                widget=forms.PasswordInput(
                                    attrs={
                                        'class': 'password-toggle auth_inputs password', 
                                        'placeholder': 'Confirm Your Password',
                                    }
                                ))
    
    # def save(self, commit=True):
    #     user = super().save(commit=False)
    #     if commit:
    #         user.save()
    #         Profile.objects.create(user=user, bio=self.cleaned_data['bio'], profile_img=self.cleaned_data['profile_img'])
    #     return user
    
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            if name == 'profile_picture':
                field.widget.attrs.update({
                    'class': 'form-control sign_up-img',
                })
            else:
                field.widget.attrs.pop('autofocus', None)
                field.widget.attrs.update({
                    'class': 'form-control password auth_inputs',
                })

    # def clean_username(self):
    #     username = self.cleaned_data.get('username')
    #     qs = User.objects.filter(username=username)
    #     if qs.exists():
    #         raise ValidationError("Username is taken")
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise ValidationError("Email is taken")

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
        ]
    
    first_name = custom_char_field('Your First Name')
    last_name = custom_char_field('Your Last Name')
    username = custom_char_field('Your username')
    email = custom_char_field('Your email address')
        
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_img', 'bio']
    
    def __init__(self, *args, **kwargs):
        super(ProfileUpdateForm, self).__init__(*args, **kwargs)
        self.fields['profile_img'].widget.attrs.update({'class': 'sign_up-img'})
    
class LoginForm(AuthenticationForm):
    username = custom_char_field('Username', 'Username')
    password = forms.CharField(label='Password', 
                                widget=forms.PasswordInput(
                                    attrs={
                                        'class': 'auth_inputs password', 
                                        'placeholder': 'Your Password',
                                        'id': 'password_login',
                                    }
                                ))
    
    def clean(self):
        username_or_email = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username_or_email and password:
            username_or_email = username_or_email.lower()
            if '@' in username_or_email:
                try:
                    user = User.objects.get(email=username_or_email)
                    username = user.username
                except User.DoesNotExist:
                    raise ValidationError('Invalid email or password')
            else:
                username = username_or_email
            
            self.user_cache = authenticate(self.request, username=username, password=password)

            if self.user_cache is None:
                raise ValidationError('Invalid email/username or password')
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

neighbornook_backend/user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.views import LoginView
from .forms import SignUpForm, ProfileUpdateForm, UserUpdateForm, LoginForm
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from django.views.generic import DetailView
import logging
from django.urls import reverse_lazy
from weather_api.weather import get_weather_context

def signup(request):
    location = '51.5072,-0.1276'
    context = get_weather_context(location)

    if request.method == 'POST':
        form = SignUpForm(request.POST, request.FILES)

        if form.is_valid():
            user = form.save()
            profile_img = form.cleaned_data.get('profile_img')
            bio = form.cleaned_data.get('bio')

            profile = user.profile

            if profile_img:
                profile.profile_img = profile_img
            if bio:
                profile.bio = bio
            profile.save()
            
            messages.success(request, f'Account created for {user.username}!')

            login(request, user)
            return redirect('home:home_loggedin')

    else:
        form = SignUpForm()

    return render(request, 'user/signup.html', {
                            'form': form,
                            **context
                            }
                    )

logger = logging.getLogger(__name__)
class CustomLoginView(LoginView):
    template_name = 'user/login.html'
    authentication_form = LoginForm

    def form_valid(self, form):
        try: 
            response = super().form_valid(form)

            user = form.get_user()
            logger.info('User %s logged in', user.username)
            messages.success(self.request, f'Welcome back {user.username}!')

            return response
        except Exception as e:
            logger.error(e)
            return super().form_invalid(form)
    
    def form_invalid(self, form):
        messages.error(self.request, 'Invalid username or password. Please try again.')
        return super().form_invalid(form)

    def get_success_url(self):
        return reverse_lazy('home:home_loggedin')
    
    def get(self, request, *args, **kwargs):
        location = '51.5072,-0.1276'
        weather_context = get_weather_context(location)
        
        context = self.get_context_data()
        
        context.update(weather_context)
        
        return self.render_to_response(context)

def custom_logout_view(request):
    location = '51.5072,-0.1276'
    context = get_weather_context(location)

    logout(request)    
    return render(request, 'user/logout.html', {**context})

@login_required
def profile(request, username):
    location = '51.5072,-0.1276'
    context = get_weather_context(location)

    user_profile = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, user=user_profile)
    profile_img = profile.profile_img.url
    profile_bio = profile.bio
    # add user events here + categories
    # user_items = Item.objects.filter(created_by=user_profile, is_sold=False)[:6]

    return render(request, 'user/profile.html', {
        'profile_img': profile_img,
        'profile_bio': profile_bio,
        'current_user': request.user,
        'user_profile': user_profile,
        'profile': profile,
        **context
    })

@login_required
def profile_update(request):
    location = '51.5072,-0.1276'
    context = get_weather_context(location)

    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('user:profile', username=request.user.username)

    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)

    return render(request, 'user/profile_update.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        **context
    })

class UserProfileView(DetailView):
    model = User
    template_name = 'user/profile.html'
    context_object_name = 'user_profile'

    def get_object(self):
        return get_object_or_404(User, username=self.kwargs['username'])

neighbornook_backend/user/templates/user/login.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}

{% block not_logged %}
    <div class="main_not_loggedin_login">
        <div class="content-section container">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group px-5">
                    <legend class="border-bottom custom-border register-title mb-4">
                        Login
                    </legend>
                    {% if messages %}
                        <div class="messages">
                            {% for message in messages %}
                                <div class="alert {{ message.tags }}">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                    
                    <div class="px-5 register_form login_form">
                        {% for field in form %}
                        {% if field.name == 'password' %}
                        <div class="input-group mb-3 input-fields">
                            {{ field|as_crispy_field }}
                            <div class="input-group-append show-container">
                                <span class="input-group-text password-toggle_login">
                                    <small class="showPasswordToggle">Show</small>
                                </span>
                            </div>
                        </div>
                        {% else %}
                            {{ field|as_crispy_field }}
                        {% endif %}
                        {% endfor %}
                    </div>
                </fieldset>

                <div class="form-group form-bottom">
                    <button class="btn auth-btn" type="submit">
                        Login
                    </button>
                    <small class="text-muted ml-2"> 
                        {% comment %} <!-- <a href="{% url 'password_reset' %}">Forgot Password?</a> --> {% endcomment %}
                    </small>
                    <small class="auth-redirect">
                        Don't have an account? 
                        <a href="{% url 'user:signup' %}" class="ml-2">
                            Sign Up
                        </a>
                    </small>
                </div>
            </form>
        </div>
    </div>
{% endblock not_logged %}

neighbornook_backend/user/templates/user/logout.html
{% extends "home/base.html" %}
{% block not_logged %}
    <div class="main_not_loggedin_login">
        <div class="logout-section">
            <h2 class="logout-title px-5 border-bottom custom-border">
                You have been logged out
            </h2>

            <div class="pt-3 mt-0 sign_again">
                <div>
                    Login again <a href="{% url 'user:login' %}">Sign In</a>
                </div>
            </div>
        </div>
    </div>
{% endblock not_logged %}

neighbornook_backend/user/templates/user/profile.html
{% extends "home/base.html" %}
{% block content %}
    <div class="container profile-container">
        <div class="profile">
            <img src="{{ profile_image }}" alt="profile image" class="profile-image {% if profile.profile_img.name == 'media/default.png' %}default-img-class{% else %}custom-img-class{% endif %}">
            <div class="profile-info">
                <div class="profile-details">
                    <p class="profile-names">{{ user_profile.first_name }} {{ user_profile.last_name }}</p>
                    <div class="profile-details_small">
                        <p>
                            <small>{{ user_profile.username }}</small> / <small>{{ user_profile.email }}</small>
                        </p>
                    </div>
                </div>
                <div class="profile-edit">
                    {% if profile.user == current_user %}
                        <a href="{% url 'communication:inbox' %}" class="profile-inbox">
                            <i class="bi bi-inbox"></i>
                        </a>
                        <button class="btn">
                            <a href="{% url 'user:profile_update' %}" class="profile-edit_link">
                                Edit Profile
                            </a>
                        </button>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    
{% endblock content %}

neighbornook_backend/user/templates/user/profile_update.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group px-5">
                    <legend class="border-bottom mb-4">
                        Profile Info
                    </legend>
                    <div class="px-5 register_form">
                        {{ user_form|crispy }}
                        {{ profile_form|crispy }}
                    </div>
                </fieldset>
                <div class="form-group form-btn">
                    <button class="btn submit-btn" type="submit">
                        Update
                    </button>
                </div>
        </form>
    </div>
{% endblock content %}

neighbornook_backend/user/templates/user/signup.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}

{% block not_logged %}
    <div class="main_not_loggedin">
        <div class="content-section container">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group px-5">
                    <legend class="border-bottom custom-border mb-4 register-title">
                        Join Your Neighborhood
                    </legend>
                    <div class="px-5 register_form">
                        {% for field in form %}
                        {% if field.name == 'password1' or field.name == 'password2' %}
                        <div class="input-group mb-3 input-fields">
                            {{ field|as_crispy_field }}
                            <div class="input-group-append show-container">
                                <span class="input-group-text password-toggle">
                                    <small class="showPasswordToggle">Show</small>
                                </span>
                            </div>
                        </div>
                        {% else %}
                        {{ field|as_crispy_field }}
                        {% endif %}
                        {% endfor %}
                    </div>
                </fieldset>

                <div class="form-group form-bottom">
                    <button class="btn auth-btn" type="submit">
                        Sign Up
                    </button>
                    <small class="auth-redirect">
                        Already have an account?
                        <a class="ml-2" href="{% url 'user:login' %}">
                            Sign In
                        </a>
                    </small>
                </div>
            </form>
        </div>
    </div>
{% endblock not_logged %}